-- Création de la base de données
CREATE DATABASE IF NOT EXISTS compta;

-- Utilisation de la base de données
USE compta;

-- Création de la table FOURNISSEUR
CREATE TABLE IF NOT EXISTS FOURNISSEUR (
    ID INT PRIMARY KEY,
    NOM VARCHAR(50) NOT NULL
);

-- Création de la table ARTICLE
CREATE TABLE IF NOT EXISTS ARTICLE (
    ID INT PRIMARY KEY,
    REF VARCHAR(10) NOT NULL,
    DESIGNATION VARCHAR(100) NOT NULL,
    PRIX DECIMAL(10,2) NOT NULL,
    ID_FOU INT,
    FOREIGN KEY (ID_FOU) REFERENCES FOURNISSEUR(ID)
);

-- Création de la table BON (bon de commande)
CREATE TABLE IF NOT EXISTS BON (
    ID INT PRIMARY KEY,
    NUMERO VARCHAR(20) NOT NULL,
    DATE_CMDE DATE NOT NULL,
    DELAI INT,
    ID_FOU INT,
    FOREIGN KEY (ID_FOU) REFERENCES FOURNISSEUR(ID)
);

-- Création de la table COMPO (composition du bon de commande)
CREATE TABLE IF NOT EXISTS COMPO (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    QTE INT NOT NULL,
    ID_ART INT,
    ID_BON INT,
    FOREIGN KEY (ID_ART) REFERENCES ARTICLE(ID),
    FOREIGN KEY (ID_BON) REFERENCES BON(ID)
);